mkdir ./repos
git clone https://github.com/apache/dubbo.git
git clone https://github.com/apache/kafka.git
git clone https://github.com/apache/skywalking.git
git clone https://github.com/apache/flink.git
git clone https://github.com/apache/rocketmq.git
git clone https://github.com/apache/shardingsphere.git
git clone https://github.com/apache/hadoop.git
git clone https://github.com/apache/pulsar.git
git clone https://github.com/apache/druid.git
git clone https://github.com/apache/zookeeper.git
git clone https://github.com/apache/dolphinscheduler.git
git clone https://github.com/apache/doris.git
git clone https://github.com/apache/cassandra.git
git clone https://github.com/apache/shenyu.git
git clone https://github.com/apache/shardingsphere-elasticjob.git
git clone https://github.com/apache/jmeter.git
git clone https://github.com/apache/beam.git
git clone https://github.com/apache/tomcat.git
git clone https://github.com/apache/seatunnel.git
git clone https://github.com/apache/storm.git